name: Test with coverage

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  sanitize-output-name:
    runs-on: ubuntu-latest
    outputs:
      output-name: coverage-${{ steps.sanitize.outputs.name }}
    steps:
      - name: Sanitize branch name
        id: sanitize
        run: |
          SAFE_NAME=$(echo "${{ inputs.branch }}" | sed 's/\//_/g')
          echo "name=$SAFE_NAME" >> $GITHUB_OUTPUT

  test-coverage:
    needs: [sanitize-output-name]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - shard: '1'
            total: '3'
          - shard: '2'
            total: '3'
          - shard: '3'
            total: '3'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests with coverage
        env:
          CI_SHARD: ${{ matrix.shard }}
          CI_SHARD_TOTAL: ${{ matrix.total }}
        run: >-
          yarn test
          --coverage
          --testLocationInResults
          --json
          --outputFile=${{ needs.sanitize-output-name.outputs.output-name }}-shard-${{ matrix.shard }}.json
          --testSequencer ./src/test/shardTestSequencer.cjs

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.sanitize-output-name.outputs.output-name }}-shard-${{ matrix.shard }}
          path: ${{ needs.sanitize-output-name.outputs.output-name }}-shard-${{ matrix.shard }}.json
          retention-days: 1

  merge-coverage-results:
    needs: [sanitize-output-name, test-coverage]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: coverage
          pattern: ${{ needs.sanitize-output-name.outputs.output-name }}-shard-*
      
      - name: Merge coverage results
        env:
          TARGET_DIR: coverage
          OUTPUT_NAME: ${{ needs.sanitize-output-name.outputs.output-name }}.json
        run: node ./src/scripts/mergeCoverage.cjs

      - name: Upload merged coverage result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.sanitize-output-name.outputs.output-name }}
          path: ${{ needs.sanitize-output-name.outputs.output-name }}.json
          retention-days: 1